starter-master/movies/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
	url(r'^$', views.home, name = 'list'),
	url(r'^(?P<id>[0-9]+)/$', views.detail, name='detail'),
]

starter-master/starter/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(__package__ + '.views',
    url(r'^$', 'landing_page', {}, 'landing_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^movies/', include('movies.urls', namespace = "movies")),
)

starter-master/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
	id = models.CharField(primary_key = True, unique = True, max_length = 200)
	title = models.CharField(max_length = 200)
	year = models.DateField()
	mpaa_rating = models.CharField(max_length = 100)
	runtime = models.IntegerField(default = 0)
	synopsis = models.CharField(max_length = 1000)

class ReleaseDate(models.Model):
	movie = models.ForeignKey(Movie)
	theater = models.CharField(max_length = 200)
	date = models.DateField()
	
class Actor(models.Model):
	id = models.CharField(primary_key = True, unique = True, max_length = 200)
	name = models.CharField(max_length = 200)

class Poster(models.Model):
	movie = models.ForeignKey(Movie)
	type = models.CharField(max_length = 200)
	link = models.CharField(max_length = 800)
	
class Showtime(models.Model):
	movie = models.ForeignKey(Movie)
	link = models.CharField(max_length = 800)
	time = models.DateTimeField() 

class Rating(models.Model):
	movie = models.ForeignKey(Movie)
	critics_rating = models.CharField(max_length = 1000)
	critics_score = models.IntegerField(default=0)
	audience_score = models.IntegerField(default=0)

class Character(models.Model):
	movie = models.ForeignKey(Movie)
	actor = models.ForeignKey(Actor)
	name = models.CharField(max_length = 200)

class AlternateID(models.Model):
	movie = models.ForeignKey(Movie)
	type = models.CharField(max_length = 200)
	link = models.CharField(max_length = 800)
	
class User(models.Model):
	name = models.CharField(max_length = 200)
	role = models.CharField(max_length = 200)
	
class Recommendation(models.Model):
	from_user = models.ForeignKey(User, related_name='sender_name')
	to_user = models.ForeignKey(User, related_name='receiver_name')
	movie = models.ForeignKey(Movie)

starter-master/starter/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    id = models.CharField(primary_key = True, unique = True, max_length = 200)
    title = models.CharField(max_length = 200)
    year = models.DateField()
    mpaa_rating = models.CharField(max_length = 100)
    runtime = models.IntegerField(default = 0)
    synopsis = models.CharField(max_length = 1000)
    def __unicode__(self):
        return "Title: " + self.title

class ReleaseDate(models.Model):
    movie = models.ForeignKey(Movie)
    theater = models.CharField(max_length = 200)
    date = models.DateField()

class Actor(models.Model):
    id = models.CharField(primary_key = True, unique = True, max_length = 200)
    name = models.CharField(max_length = 200)
    def __unicode__(self):
        return "Name: " + self.name

class Poster(models.Model):
    movie = models.ForeignKey(Movie)
    type = models.CharField(max_length = 200)
    link = models.CharField(max_length = 800)

class Rating(models.Model):
    movie = models.ForeignKey(Movie)
    critics_rating = models.CharField(max_length = 1000)
    critics_score = models.IntegerField(default=0)
    audience_score = models.IntegerField(default=0)

class Character(models.Model):
    movie = models.ForeignKey(Movie)
    actor = models.ForeignKey(Actor)
    name = models.CharField(max_length = 200)

class AlternateID(models.Model):
    movie = models.ForeignKey(Movie)
    type = models.CharField(max_length = 200)
    link = models.CharField(max_length = 800)

class User(models.Model):
    name = models.CharField(max_length = 200)
    role = models.CharField(max_length = 200)

class Recommendation(models.Model):
    from_user = models.ForeignKey(User, related_name='sender_name')
    to_user = models.ForeignKey(User, related_name='receiver_name')
    movie = models.ForeignKey(Movie)

starter-master/movies/views.py
from django.shortcuts import get_object_or_404, render
from .models import Movie
 

# Create your views here.

def home(request):
    movies_list = Movie.objects.order_by('title')[:5]
    context = {'movies_list': movies_list}
    return render(request, 'movie.html', context)
	
def detail(request, id):
    movie = get_object_or_404(Movie, pk=id)
    return render(request, 'detail.html', {'movie': movie})
	
def signup(request):
	return render(request, 'signup.html')

starter-master/starter/views.py
from django.shortcuts import get_object_or_404, render
from .models import Movie

def landing_page(request):
    return render(request, "starter/landing_page.html", {'movie_list' : Movie.objects.all})
	
def movie_item(request, movie):
	return render(request, "starter/list_item.html", Movie)
	
def login(request, Movie):
	return render(request, "starter/login.html", Movie)
	
def signup(request):
	return render(request, "starter/signup.html")

starter-master/movies/templates/detail.html
<h1>{{ movie.title }}</h1>
<ul>
{% for character in movie.character_set.all %}
    <li>{{ character.name }}</li>
{% endfor %}
</ul>

starter-master/movies/templates/index.html
{% if movies_list %}
    <ul>
    {% for movie in movies_list %}
        <li>
			<a href="{% url 'movies:detail' movie.id %}">
				{{ movie.title}}
			</a>
		</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No movies are available.</p>
{% endif %}

starter-master/movies/templates/list.html
<h1>{{ movie.title }}</h1>
<ul>
{% for character in movie.character_set.all %}
    <li>{{ character.name }}</li>
{% endfor %}
</ul>

starter-master/starter/templates/starter/base.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>
  <head>
    <title>
      Foundation for Learning Equality
    </title>

  </head>

  <body>
	<div class="navbar navbar-default" role="navigation">
		{% include "starter/header.html" %}
	</div>
	
	<div>
		{% include "starter/filters.html" %}    
	</div>

	<div class="movies_list">
		<ul>
		{% for movie in movie_list %}
			<li>{% include "starter/list_item.html"%}<li>
		{% endfor %} 
		</ul>
	</div>
	
  </body>
</html>

starter-master/starter/templates/starter/filters.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class = "options">
        <!-- Collect the nav links, forms, and other content for toggling -->
          <ul class = "filter_list">
            <button type="submit" class="btn filter_btn">Recommendations</button>
			<button type="submit" class="btn filter_btn">Friends</button>
			<button type="submit" class="btn filter_btn">Calendar</button>
			
			
			<hr style="border-top: dotted 2px; color: #D7D7D7" />
			<li><B>Search Options:</B></li>
			
			<li class = "filter_label">Genre
              <select  class="filter_dropdown">
				<option><a href="#">All</a></option>
				<option><a href="#">Action</a></option>
                <option><a href="#">Adventure</a></option>
				<option><a href="#">Animated</a></option>
				<option><a href="#">Comedy</a></option>
				<option><a href="#">Drama</a></option>
				<option><a href="#">Fantasy</a></option>
				<option><a href="#">Horror</a></option>
				<option><a href="#">Sci-Fi</a></option>
				<option><a href="#">Thriller</a></option>
				<option><a href="#">War</a></option>
              </select> 
            </li>
			
			<li class = "filter_label">Rating
              <select class="filter_dropdown">
			  <option><a href="#">All</a></option>
				<option><a href="#">G</a></option>
                <option><a href="#">PG</a></option>
				<option><a href="#">PG-13</a></option>
				<option><a href="#">R</a></option>
				<option><a href="#">Unrated</a></option>
              </select> 
            </li>

			<li class="filter_label">Order 
              <select class="filter_dropdown">
				<option><a href="#">All</a></option>
                <option><a href="#">Alphabetical</a></option>
				<option><a href="#">Top Grossing</a></option>
                <option><a href="#">Score</a></option>				
				<option><a href="#">Release Date</a></option>				
              </select> 
			</li>
			
			<li class="filter_label">Show 
              <select class="filter_dropdown">
				<option><a href="#">All</a></option>
                <option><a href="#">20 per page</a></option>
                <option><a href="#">50 per page</a></option>
				<option><a href="#">100 per page</a></option>
              </select> 
			</li>
			
			<li  class = "filter_label" ><input type="checkbox"> Favorites</input></li>
			
			<li  class = "filter_label" ><input type="checkbox"> Seen by Friends</input></li>
			
			<li class = "filter_label"><input type="checkbox"> In Theaters Only</input></li>
			
			<li class = "filter_label" ><input type="checkbox"> DVD Released</input></li>
			
			
			<br/>
	
			<li><button type="submit" class="btn btn-default" style="float:right; margin-right:20px;">Search</button></li>
			  
          </ul>
</div>

starter-master/starter/templates/starter/header.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#"> <img src="{% static 'fle_200_45.jpg' %}" alt="FLExster" /></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search for movies, actors, keywords etc.">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
				{% if user %}
					<li class="greeting">Hello, {{ user.username }}<li>
				{% else %}
					<li> <a href = "login" class = "greeting">Click to Login or Register</a> <li>
				{% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

starter-master/starter/templates/starter/landing_page.html
{% extends "starter/base.html" %}

starter-master/starter/templates/starter/list_item.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class = "movie_item">
	<div class = "movie_poster">
		<div class = "poster">
			<img src="{{ movie.poster_set.last.link}}" alt="No Poster Found" style="width:100%; height:100%;">
		</div>
	</div>

	<div class = "movie_details">
		<div class="movie_title_container">
		<div class="movie_float_right">
				<a href="#" class="movie_btn">Seen It</a>
				<a href="#" class="movie_btn">Recommend</a>
				<a href="#" class="movie_btn">Add to Favorites</a>
		</div>
		<div class="movie_title">
				{{ movie.title }}
		</div>
	</div>
	
	<div class="rating">
		 {% for  i in "xxxxxxxxxx" %}
			<span>☆</span>
		 {% endfor %}

		<ul>
			<li><B>{{movie.mpaa_rating}} | {{movie.runtime}} min | {{movie.year}}</B></li>
			<br/>
			
			{{movie.synopsis}}
			
			<br/>
			<h5> <B>Abridged Cast </B></h5>
			{% for character in movie.character_set.all %}
				<li>{{ character.actor.name}} as <i>{{character.name}}</i></li>
			{% endfor %}

			<br/>
			<B>Released</B>
			{% for release in movie.releasedate_set.all %}
				<li> {{ release.theater }}: {{ release.date }}</li>
			{% endfor %}
		</ul>
	</div>
		<button class="btn detail_button" style="float:bottom;">View More Details</button>
		<button class="btn detail_button" style="float:bottom;">Tickets & Showtimes</button>
</div>

starter-master/starter/templates/starter/login.html
 {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
 
 <div class="login_body">
		<i> This page has not been implemented, click "Login" to continue </i>
        <input type="text" placeholder = "Enter username" />
		<input type="password" placeholder = "Enter password" />
        <input type="submit" value="Login" onclick="window.location='..'" />
</div>

starter-master/starter/templates/starter/movie.html
Movie
<h1>{{ movie.title }}</h1>
<ul>
	<li>{{movie.mpaa_rating}}</li>
{% for character in movie.character_set.all %}
    <li>{{ character.name }}</li>
{% endfor %}
{% for release in movie.releasedate_set.all %}
    <li>{{ release.date }}</li>
	<li>{{ release.theater }}</li>
{% endfor %}
</ul>

starter-master/starter/templates/starter/movie_list.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class="movies_list">
	{% for movie in movie_list %}
    <li>{{ movie.title }}</li>
{% endfor %}
</div>

starter-master/starter/templates/starter/signup.html
 {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
 
		<i> This page has not been implemented, click "Register" to continue </i>
        <input type="text" placeholder = "Name" />
		<input type="text" placeholder = "Username" />
		<input type="password" placeholder = "Enter password" />
		<input type="password" placeholder = "Enter password again" />
		
		<select name = "role" placeholder="Select a Role">
			<option>Administrator</option>
			<option>User</option>
		</select>
		
		<input type="submit" value="Register" />